### ISSUE TITLE
API: Post table - GET/POST - Get all posts/Create a post

### ISSUE THREAD

**Issue by JosteinRuen** [boolean-uk/team-dev-server-ex-2410-team1#13]

**Comment by IbbiSecka** [comment]
Created a post domain model which is an instance of the Post database. Updated the getAll function on the post controller to actually fetch posts from the database.

**Comment by Panfi98** [comment]
BRANCH: [panfi98&IbbiSecka-issue_13-GET&POST_posts](https://github.com/boolean-uk/team-dev-server-ex-2410-team1/tree/panfi98%26IbbiSecka-issue_13-GET%26POST_posts)

**Description**
Get all posts: Implement funcitonality to actually get all posts from database. The endpoint needs to get all data from the domain, which in turn interacts with prisma to extract everything. getAll will provide a list with json post objects.

**route: ** 
GET - {domain}/posts

**RESPONSE:**
**->status**
200 OK, 401 Fail

**->object:** 
```
{
  "status": "string",
  "data": {
    "posts": [
      {
        "id": 0,
        "content": "string",
        "createdAt": "string",
        "updatedAt": "string",
        "author": {
          "id": 0,
          "cohortId": 0,
          "role": "string",
          "firstName": "string",
          "lastName": "string",
          "bio": "string",
          "githubUrl": "string",
          "profileImageUrl": "string"
        }
      }
    ]
  }
}
```

**route: ** 
POST - {domain}/posts

**Description**
Create: creates post, needs only content the author id is hardcoded for now to be 1, the post id is auto incremented

**RESPONSE:**
**->status**
201 Created, 400 Bad Request

**->object:** 
```
{
  "status": "string",
  "data": {
    "post": {
      "id": 0,
      "content": "string"
    }
  }
}
```

**Comment by allendewilzin** [comment]
Looks good. 👍🏻

**Comment by Panfi98** [comment]
create works, NEEDS to be adjusted and improved before moving forward, get all is broken for some reason for now...

**Comment by Panfi98** [comment]
The endpoint works now on swagger, but not with the frontend.( the issue might be in frontend)

**Comment by allendewilzin** [comment]
Let me know what the issue was

**Comment by Panfi98** [comment]
The frontend simply does not run with this code in the backgound. Backend runs, posts are created & saved and shown from the database, but frontend gets this erroe r![Image](https://github.com/user-attachments/assets/2e639a06-184c-4210-9aa3-a14b00905a6a)

**Comment by allendewilzin** [comment]
Let me know when you resolved it. As there might be changes to be done on UI. 

Raise it with Scrum master
