### ISSUE TITLE
Add DELETE Post API Endpoint

### ISSUE THREAD

**Issue by alinjo** [boolean-uk/team-dev-server-ex-2410-team1#16]
Add deletePost function in src/controllers/post.js for success and error responses. 
Add DELETE route in src/routes/post.js.
Add DELETE logic in src/domain/post.js 
Update OpenAPI specification. 

Method: DELETE
URL: /posts/{id}

Request Parameters
Path Parameter: ID of the post to be deleted.

Response Body:
```
{
  "status": "success",
  "data": {
    "post": {
      "id": 1,
      "content": "string",
      "userId": 1
    }
  }
}
```

Error Responses:

404 Not Found
Description: Post with the specified ID was not found.
```
{
  "status": "string",
  "data": {
    "error": "string"
}
```

500 Internal Server Error
Description: Server encountered an unexpected error.
```
{
  "status": "string",
  "data": {
    "error": "string"
  }
}
```

**Comment by allendewilzin** [comment]
Issue breakdown required

### Endpoint Name
Method: GET/POST/PUT/DELETE/PATCH
Url: `post/{id}`
Request Body (if Applicatible)
```json
{
 'example':'example'
}
```

Response Body
```json
{
 'Responseexample':'example'
}
```

Models Changes (Task based)
- [] Task 1 
- [] Task 2
DB Changes (Task based)
- [] Task 1 
- [] Task 2

The above can be used for a template to do all the endpoints but should be used for yourself as a guideline to ensure you have all the steps included when doing to work.

**Comment by dogezen** [comment]
The SUCCESSFUL response should match the pattern for all other responses:

```json
{
  "status": "success",
  "data": {
    "post": {
       ... data of the post that was just deleted
    }
  }
}
```

the NOT found response should also match the same pattern:

```json
{
  "status": "error",
  "data": {
    "error": "Post does not exist"
  }
}
```

Also make a note in the issue that you'll update the OpenAPI YAML Spec File with the endpoint

**Comment by dogezen** [comment]
The title of the issue is also unclear: probably best to change it to `Add DELETE Post API Endpoint`

Also, can you include details of what files you need to change: do you need to update the domain? the controller? the routers files? It's unclear if the code is already there and you just need to add the route or you need to write up the router, controller and domain code.
