### ISSUE TITLE
API: User table - GET - Get all users by last name

### ISSUE THREAD

**Issue by JosteinRuen** [boolean-uk/team-dev-server-ex-2410-team1#19]

**Comment by allendewilzin** [comment]
Issue breakdown required

### Endpoint Name
Method: GET/POST/PUT/DELETE/PATCH
Url: `post/{id}`
Request Body (if Applicatible)
```json
{
 'example':'example'
}
```

Response Body
```json
{
 'Responseexample':'example'
}
```

Models Changes (Task based)
- [] Task 1 
- [] Task 2
DB Changes (Task based)
- [] Task 1 
- [] Task 2

The above can be used for a template to do all the endpoints but should be used for yourself as a guideline to ensure you have all the steps included when doing to work.
