### ISSUE TITLE
API: User table - GET - Get all users by name

### ISSUE THREAD

**Issue by JosteinRuen** [boolean-uk/team-dev-server-ex-2410-team1#20]
## Functions to implement in domain/user.js:
- Add function findManyByLastName (basically a copy of findManyByLastName
- Add function findByName that uses the functions above to check if an input string is either a full name or only first/last, and then return the user(s).

## Endpoint - getAll
the parameter will be name, which can be either a first/lastname or a full name. The FindByName functon will take care of this. 
Method: GET
URL: users?name=Joe
Success:
Response code: 200
Response body type: array of User (s)
``` 
{
  "status": "success",
  "data": {
    "users": [
      {
        "id": 1,
        "cohort_id": 1,
        "role": "STUDENT",
        "firstName": "Joe",
        "lastName": "Bloggs",
        "email": "student@test.com",
        "biography": "Hello, world!",
        "githubUrl": "student1"
      }
    ]
  }
}
``` 

Error conditions:  
404 : Error: Not found
``` 
{
  "status": "fail",
  "message": "User not found"
}
```

**Comment by allendewilzin** [comment]
Issue breakdown required

### Endpoint Name
Method: GET/POST/PUT/DELETE/PATCH
Url: `post/{id}`
Request Body (if Applicatible)
```json
{
 'example':'example'
}
```

Response Body
```json
{
 'Responseexample':'example'
}
```

Models Changes (Task based)
- [] Task 1 
- [] Task 2
DB Changes (Task based)
- [] Task 1 
- [] Task 2

The above can be used for a template to do all the endpoints but should be used for yourself as a guideline to ensure you have all the steps included when doing to work.

**Comment by allendewilzin** [comment]
When using a webhook for URL parameters a value should be provied. `/users?name=AJ&lastname=DeWilzin`

What parameters will you be able to search for?

**Comment by allendewilzin** [comment]
Looks Good. 👍🏻
