### ISSUE TITLE
API: Post table - Put- edit post by postId

### ISSUE THREAD

**Issue by IbbiSecka** [boolean-uk/team-dev-server-ex-2410-team1#21]
Add updatePost function in src/controllers/post.js for success and error responses.
Add put/:id route in src/routes/post.js.
Add put/:id logic in src/domain/post.js
Update post path in OpenAPI specification.

Method: PUT
URL: /posts/{id}

Request Parameters
Path Parameter: ID of the post to be modified.

Response Body: 

```
200 Post updated successfully
{
  "status": "string",
  "data": {
    "post": {
      "id": 0,
      "content": "string"
    }
  }
}
```

Error Responses:

```
400 Invalid ID supplied
Description: Post with the specified ID is invalid.

{
  "status": "string",
  "data": {
    "error": "string"
  }
}
```

404 Not Found
Description: Post with the specified ID was not found.

```
{
  "status": "string",
  "data": {
    "error": "string"
  }
}
```

500 Internal Server Error
Description: Server encountered an unexpected error.

```
{
  "status": "string",
  "data": {
    "error": "string"
  }
}
```

**Comment by dogezen** [comment]
Good one, missing:

a) can anyone update any post? or can I just update posts that I have created?
b) teachers should be able to update / edit any post by any user
c) what are you expecting the `req.body` to be? any required fields? any optional fields? any constraints on the fields? for example, can I send an empty PUT request? can I send an put request with content = ""?

**Comment by allendewilzin** [comment]
👍🏻
