### ISSUE TITLE
Separate behavior for teachers and students for /users, add remaining fields to model

### ISSUE THREAD

**Issue by gremble0** [boolean-uk/team-dev-server-ex-2410-team1#23]
## For all endpoints
`/users` endpoints should behave differently for students and teachers. For students the responses should look like:
```json
{
  "status": "success",
  "data": {
    "user": {
      "id": 1,
      "firstName": "Alex",
      "lastName": "Walker",
      "userName": "Alex Walker",
      "githubUsername": "alex-walker",
      "email": "alex.walker@boolean.co.uk",
      "mobile": "07890 123456",
      "role": "STUDENT",
      "specialism": "Software Developer",
      "cohort_id": 4,
      "start_date": "mm-yyyy",
      "end_date": "mm-yyyy",
      "biography": "Hello there!",
    }
  }
}
```

For teachers:
```json
{
  "status": "success",
  "data": {
    "user": {
      "id": 2,
      "firstName": "Dylan",
      "lastName": "Green",
      "userName": "Dylan Green",
      "githubUsername": "dylan-green",
      "email": "teacher@test.com",
      "mobile": "07654 321098",
      "role": "TEACHER",
      "specialism": "Software Developer",
      "job_title": "Software Development Instructor",
      "biography": "Hello there!",
    }
  }
}
```

## Patch endpoint
For the patch endpoint only users logged in as teachers should be able to change the `cohort_id` or `role` of other users, students should only be able to change their profile credentials. Students should receive a `403` when attempting to update fields they're not permitted to

## Remaining model changes
To reflect the usage in the frontend the `githubUrl` field should be renamed to `githubUsername`. Also the fields `startDate` and `endDate` needs to be added for students.

**Comment by allendewilzin** [comment]
So teachers will only be able to see teachers and Students will only be able to see students?

**Comment by allendewilzin** [comment]
Is this endpoint used to get a single profile information or a list of users?

**Comment by gremble0** [comment]
This is not adding any new endpoints, only changing the behavior of the existing ones. The api docs already specifies ```Only users with a TEACHER role can update the cohort_id or role. Users with Students role can only update their own details.``` so it should implement this. Both students and teachers should see each other, but if the user requests a student the response should be different from a teacher @allendewilzin

**Comment by allendewilzin** [comment]
👍🏻 Good comment. If that was said in the first comment would have understand it.
