### ISSUE TITLE
API: Post table - GET - Get post by id

### ISSUE THREAD

**Issue by thomaafl** [boolean-uk/team-dev-server-ex-2410-team1#30]
Add getPostById function in src/controllers/post.js for success and error responses.
Add get/:id route in src/routes/post.js.
Add get/:id logic in src/domain/post.js
Update post path in OpenAPI specification.

Method: GET
URL: /posts/{id}

Request Parameters
Path Parameter: ID of the post to be deleted.

Response Body:

```
{
  "status": "string",
  "data": {
    "post": {
      "id": 0,
      "content": "string"
    }
  }
}
```

Error Responses:

400 Invalid ID supplied
Description: Post with the specified ID is invalid.

```
{
  "status": "string",
  "data": {
    "error": "string"
  }
}
```

404 Not Found
Description: Post with the specified ID was not found.

```
{
  "status": "string",
  "data": {
    "error": "string"
  }
}
```

500 Internal Server Error
Description: Server encountered an unexpected error.

```
{
  "status": "string",
  "data": {
    "error": "string"
  }
}
```

**Comment by allendewilzin** [comment]
Great spec. 

Please do all specs as per above. 

:+1:
