### ISSUE TITLE
API: Get comments for posts

### ISSUE THREAD

**Issue by JosteinRuen** [boolean-uk/team-dev-server-ex-2410-team1#37]
Description
Get all comments for a post, based on the postid: Implementing functionality to get comments for a spesific post according to the postid from database.

route: 
GET - /posts/{id}/comments

RESPONSE:
->status
200 OK

{
  "status": "success",
  "data": {
    "id": 1,
    "content": "yo",
    "postId": 1,
    "author": {
      "id": 1,
      "cohortId": null,
      "firstName": null,
      "lastName": null,
      "email": "student@test.com",
      "bio": null,
      "githubUrl": null,
      "role": "STUDENT"
    }
  }
}

RESPONSE:

404 NOT FOUND

{
"status": "error"
"message": "no comments found for this post"
}

400 BAD REQUEST

401 UNAUTHORIZED

**Comment by allendewilzin** [comment]
Does the post have a createdDateTime field in the DB? 

Would be great to arrange comments by decending order and have the latest comments always first.

**Comment by alihaiderkhannn** [comment]
Not right now, but Daniil or Herman is on it.

**Comment by Panfi98** [comment]
should I do it in separate issue?

**Comment by allendewilzin** [comment]
yes please

**Comment by alihaiderkhannn** [comment]
He is on it. Can I go on with this issue?
