### ISSUE TITLE
API post: add created at and updated at to posts

### ISSUE THREAD

**Issue by Panfi98** [boolean-uk/team-dev-server-ex-2410-team1#41]
Schema file should include created at and updatet at in the schema file. The posts from the GET route {domain}/posts should include created at and updated at. 

Routes potentially effected:

GET route {domain}/posts
POST route {domain}/posts (the date should automatically be initiated)
PUT route {domain}/posts/id 
GET route {domain}/posts/id

Example:
```
"posts": [
      {
        "id": 0,
        "content": "string",
        "createdAt": "date time",
        "updatedAt": "date time",
        "author": {
          "id": 0,
          "cohort_id": 0,
          "role": "string",
          "firstName": "string",
          "lastName": "string",
          "bio": "string",
          "githubUsername": "string",
          "profileImageUrl": "string"
        }
      }
    ]
```

**Comment by dogezen** [comment]
You should update the PRISMA Model for Posts to be:

```
model Post {
  ...
  createdAt               DateTime            @default(now())
  updatedAt              DateTime            @updatedAt
  ...
}
```

This means that prisma automatically fills in the createdAt and the updatedAt columns for you correctly, without you needing to write any code for it.
