### ISSUE TITLE
/users endpoints

### ISSUE THREAD

**Issue by gremble0** [boolean-uk/team-dev-server-ex-2410-team1#9]
Update database model to include all fields in the create user form.

https://www.figma.com/design/j9QIHvgM0wOVw3xDe9KdWB/My-Copy%3A-Cohort-Manager-app---Designs?node-id=228-41540&t=ep6tuwERh4cTL9t4-0

## Model changes
- Add field `mobile` to `User` class
- Add field `specialism` to `User` class
- Add field `imageUrl` to `User` class

## Add deleteById endpoint
Method: DELETE
Url: /users/{id}
Response body type: `User`
Error conditions:
- No user with `id`:
    - Response body:
```json
{
  "status": "fail",
  "message": "User not found"
}
```

## Fix /users PATCH endpoint
Existing implementation of PATCH endpoint only consisted of hardcoded responses and did not communicate with the database. Now it stores patched changes to the given user persistently

Method: PATCH
Url: /users/{id}
Response body type: `User`

**Comment by thomaafl** [comment]
lovely code, approved!
